name: audio_player
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  audio_video_progress_bar: ^2.0.1
  just_audio: ^0.9.35
  just_audio_background: ^0.0.1-beta.10
  rxdart: ^0.27.7
  just_audio_cache: ^0.1.2
  flutter_bloc: ^8.1.3
  audioplayers: ^5.2.0
  audio_session: ^0.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  uses-material-design: true
  assets:
    - assets/
    - assets/audio/